# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[graph]
# The network graph to use when analyzing the dependency tree
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# The lint level for security vulnerabilities
vulnerability = "deny"
# The lint level for unmaintained crates
unmaintained = "warn"
# The lint level for crates that have been yanked from their source registry
yanked = "warn"
# The lint level for crates with security notices. Note that as of
# 2019-12-17 there are no security notice advisories in
# https://github.com/rustsec/advisory-db
notice = "warn"
# A list of advisory IDs to ignore. Note that ignored advisories will still
# emit a note when they are encountered.
ignore = [
    # "RUSTSEC-0000-0000",
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# The graph highlighting used when creating dotgraphs for crates
# with multiple versions
# * lowest-version - The path to the lowest versioned duplicate is highlighted
# * simplest-path - The path to the version with the fewest edges is highlighted
# * all - Both lowest-version and simplest-path are used
highlight = "all"
# List of crates that are allowed. Use to work around an un-warned-about license
# mismatch in one of the dependency crates (for example an MIT-licensed
# dependency being used by an Apache-2.0 crate)
# Note that this also works for git dependencies!
allow = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
# List of crates to deny
deny = [
    # Each entry the name of a crate and a version range. If version is
    # not specified, all versions will be matched.
    #{ name = "ansi_term", version = "=0.11.0" },
]
# Skip specific crates during duplicate detection
skip = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
# Skip crates that have the specified version requirements
skip-tree = [
    #{ name = "ansi_term", version = "=0.11.0" },
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not in
# the allow list is encountered
unknown-git = "warn"
# List of URLs for allowed crate registries. Defaults to the crates.io index
# if not specified. If it is specified but empty, no registries are allowed.
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []

[licenses]
# The lint level for crates which do not have a license detectable by
# either crates.io or SPDX. This currently only works for crates which
# publish to crates.io.
unlicensed = "deny"
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    "MPL-2.0",
]
# List of explicitly disallowed licenses
deny = [
    #"GPL-3.0",
]
# Lint level for licenses considered copyleft
copyleft = "warn"
# Blanket approval or denial for OSI-approved or FSF Free/Libre licenses
# * both - The license will be approved if it is both OSI-approved *AND* FSF
# * either - The license will be approved if it is either OSI-approved *OR* FSF
# * osi-only - The license will be approved if it is OSI-approved *AND NOT* FSF
# * fsf-only - The license will be approved if it is FSF *AND NOT* OSI-approved
allow-osi-fsf-free = "either"
# Lint level for licenses that are considered non-free
non-free = "deny"
# Lint level for licenses that are considered non-free but also allow
# commercial use (non-freely redistributable)
non-free-commercial = "deny"
# Lint level for licenses that are considered non-free but also allow
# commercial use and can be used in redistributable software
non-free-redistributable = "deny"
# List of explictly allowed license identifiers
allow-identifiers = [
    # "MIT",
]
# List of explictly disallowed license identifiers
deny-identifiers = [
    # "GPL-3.0",
]
# List of explictly allowed license names
allow-names = [
    # "MIT",
]
# List of explictly disallowed license names
deny-names = [
    # "GPL-3.0",
]
# The confidence threshold for detecting a license from a license text.
# The higher the value, the more closely the license text must match the
# canonical license text of a valid SPDX license file.
confidence-threshold = 0.8

[licenses.private]
# If true, ignores workspace crates that aren't published, or are only
# published to private registries
ignore = false
# One or more private registries that you might publish crates to, if a crate
# is only published to private registries, and ignore is set to true, the crate
# will not have its license(s) checked
registries = [
    #"https://sekretz.com/registry
]
